Repository datasciencecampus/transport-network-performance, pull requests merged in 2023-08, with the labels that each got.

#30 17 pop merge resample
  .github/workflows/python-package.yml
  CONTRIBUTING.md
  notebooks/population/grid_pop_experiment.py
  requirements.txt
  src/transport_performance/utils/placeholder.py
  src/transport_performance/utils/raster.py
  tests/utils/test_raster.py
Labels: enhancement, small, should

#35 Refactored daily summaries
  .github/workflows/python-package.yml
  pipeline/gtfs/01-validate-gtfs.py
  src/transport_performance/gtfs/validation.py
  src/transport_performance/utils/defence.py
  tests/gtfs/test_validation.py
Labels: small

#44 28 preprocess raster pop
  requirements.txt
  src/transport_performance/population/__init__.py
  src/transport_performance/population/rasterpop.py
  src/transport_performance/population/vectorpop.py
  src/transport_performance/utils/test_utils.py
  tests/population/test_rasterpop.py
  tests/utils/test_raster.py
Labels: enhancement

#34 29 clip osm
  .github/workflows/python-package.yml
  pipeline/gtfs/01-validate-gtfs.py
  pipeline/gtfs/config/01-validate-gtfs.toml
  requirements.txt
  src/transport_performance/gtfs/gtfs_utils.py
  src/transport_performance/gtfs/routes.py
  src/transport_performance/gtfs/validation.py
  src/transport_performance/osm/osm_utils.py
  src/transport_performance/utils/defence.py
  tests/gtfs/test_gtfs_utils.py
  tests/gtfs/test_validation.py
  tests/osm/test_osm_utils.py
  tests/utils/test_defence.py
Labels: enhancement

#100 Adjust check_parent_dir_exists() to fix bugs
  pipeline/gtfs/01-validate-gtfs.py
  src/transport_performance/utils/defence.py
  tests/gtfs/test_gtfs_utils.py
  tests/gtfs/test_validation.py
  tests/utils/test_defence.py
Labels: small, GTFS

#104 84 path warning
  notebooks/urban_centres/poc_urban_centres.py
  src/transport_performance/urban_centres/raster_uc.py
  tests/urban_centres/test_urban_centres.py
Labels: small, urban centre

#107 Added temp dir to `test_viz_stops_defence`
  tests/gtfs/test_validation.py
Labels: bug, x-small, GTFS
