Repository datasciencecampus/transport-network-performance, pull requests merged in 2023-11, with the labels that each got.

#190 186 filter to date method in gtfsinstance
  .github/workflows/all-os-tests.yml
  .github/workflows/python-package.yml
  notebooks/e2e/config/e2e.toml
  notebooks/e2e/e2e.py
  src/transport_performance/gtfs/gtfs_utils.py
  src/transport_performance/utils/defence.py
  tests/gtfs/test_gtfs_utils.py
Labels: enhancement, GTFS

#176 docs: Attribution notices for fixtures & lookup
  LICENSE.note
Labels: documentation

#198 197 improve ci
  .github/workflows/all-os-tests.yml
  .github/workflows/integration-tests.yml
  .github/workflows/python-package-linux.yml
  .github/workflows/python-package-mac.yml
  .github/workflows/python-package-windows.yml
  .github/workflows/sphinx-render.yml
Labels: bug, enhancement

#192 E2e notebooks
  notebooks/e2e/config/e2e_leeds.toml
  notebooks/e2e/config/e2e_london.toml
  notebooks/e2e/config/e2e_marseille.toml
  notebooks/e2e/config/e2e_newport.toml
  notebooks/e2e/e2e_leeds.py
  notebooks/e2e/e2e_london.py
  notebooks/e2e/e2e_marseille.py
  notebooks/e2e/e2e_newport.py
Labels: x-small

#206 174 develop metrics module
  .gitignore
  notebooks/metrics/metrics_experiments.py
  requirements.txt
  scripts/prep-metrics-fixtures.py
  src/transport_performance/_metrics/tp_utils.py
  src/transport_performance/metrics.py
  src/transport_performance/utils/io.py
  tests/_metrics/metrics_fixtures.py
  tests/_metrics/test_tp_utils.py
  tests/data/metrics/mock_centroid_gdf.pkl
  tests/data/metrics/mock_pop_gdf.pkl
  tests/data/metrics/mock_raster_input.tif
  tests/data/metrics/mock_tt.parquet
  tests/data/metrics/mock_urban_centre.pkl
  tests/test_metrics.py
  tests/utils/test_io.py
Labels: medium, metrics
