Repository datasciencecampus/transport-network-performance, pull requests merged in 2023-09, with the labels that each got.

#113 52 pop plot no uc
  requirements.txt
  src/transport_performance/population/rasterpop.py
Labels: x-small, population

#117 109 develop windows os ci
  .github/workflows/all-os-tests.yml
  .github/workflows/python-package.yml
  requirements.txt
  src/transport_performance/urban_centres/raster_uc.py
  src/transport_performance/utils/defence.py
  tests/gtfs/test_validation.py
  tests/utils/test_defence.py
Labels: enhancement

#110 102 setup sphinx
  .github/workflows/sphinx-render.yml
  .gitignore
  README.md
  docs/Makefile
  docs/README.md
  docs/make.bat
  docs/source/_static/custom.css
  docs/source/_static/dsc.png
  docs/source/_static/favicon.ico
  docs/source/_templates/autosummary/base.rst
  docs/source/_templates/autosummary/class.rst
  docs/source/_templates/autosummary/module.rst
  docs/source/_templates/footer.html
  docs/source/conf.py
  docs/source/explanation/index.rst
  docs/source/how_to/index.rst
  docs/source/index.rst
  docs/source/reference/coverage.rst
  docs/source/reference/index.rst
  docs/source/tutorials/index.rst
  requirements.txt
Labels: documentation, enhancement, small

#127 Remove hard coded zoom value
  src/transport_performance/gtfs/validation.py
Labels: x-small, technical debt, GTFS

#112 HTML outputs for GTFS data.
  .gitignore
  requirements.txt
  src/transport_performance/gtfs/gtfs_utils.py
  src/transport_performance/gtfs/report/css_styles/styles.css
  src/transport_performance/gtfs/report/html_templates/evaluation_template.html
  src/transport_performance/gtfs/report/html_templates/stops_template.html
  src/transport_performance/gtfs/report/html_templates/summary_template.html
  src/transport_performance/gtfs/report/report_utils.py
  src/transport_performance/gtfs/routes.py
  src/transport_performance/gtfs/validation.py
  src/transport_performance/osm/osm_utils.py
  src/transport_performance/utils/defence.py
  tests/data/gtfs/report/html_template.html
  tests/gtfs/report/test_report_utils.py
  tests/gtfs/test_gtfs_utils.py
  tests/gtfs/test_routes.py
  tests/gtfs/test_validation.py
  tests/osm/test_osm_utils.py
  tests/utils/test_defence.py
Labels: enhancement, GTFS

#138 121 resample file directory
  src/transport_performance/utils/raster.py
  tests/utils/test_raster.py
Labels: bug, x-small, population

#137 Converted print statements to errors/warnings; updated tests
  src/transport_performance/gtfs/validation.py
  tests/gtfs/test_validation.py
Labels: x-small, technical debt, GTFS

#140 57 rasterpop coverage
  tests/population/test_rasterpop.py
  tests/population/test_vectorpop.py
Labels: small, population

#115 feat: Tests for invalid data in GTFS dataset
  conftest.py
  notebooks/gtfs/check_unmatched_id_warnings.py
  tests/gtfs/test_validation.py
Labels: small, technical debt, GTFS

#143 71 open bbox filter gtfs bbox to be a polygon
  src/transport_performance/gtfs/gtfs_utils.py
  tests/gtfs/test_gtfs_utils.py
Labels: enhancement

#139 108 update is expected filetype defence function to check multiple extensions
  src/transport_performance/utils/defence.py
  tests/gtfs/test_validation.py
  tests/osm/test_osm_utils.py
  tests/utils/test_defence.py
  tests/utils/test_raster.py
Labels: enhancement

#141 118 test handle path like
  src/transport_performance/utils/defence.py
  tests/utils/test_defence.py
Labels: small

#132 119 e2e example
  notebooks/e2e/config/e2e.toml
  notebooks/e2e/e2e.py
  requirements.txt
Labels: small, could, research

#146 58 utils raster coverage
  src/transport_performance/utils/raster.py
  tests/utils/test_raster.py
Labels: small, could, population

#144 53 54 56 population defence
  src/transport_performance/population/rasterpop.py
  tests/population/test_rasterpop.py
Labels: small, could, population

#149 Add back to index option to GTFS report
  src/transport_performance/gtfs/validation.py
Labels: GTFS HTML

#142 80 default out pth argument in transport performanceosmosm utilspy
  src/transport_performance/osm/osm_utils.py
  tests/osm/test_osm_utils.py
Labels: enhancement, x-small, OSM

#150 70 optional arg for viz stops to only plot stop ids in stop timestxt
  src/transport_performance/gtfs/validation.py
  tests/gtfs/test_validation.py
Labels: enhancement

#136 135 osm filtered outputs not readable by r5py
  notebooks/e2e/config/e2e.toml
  notebooks/e2e/e2e.py
  src/transport_performance/osm/osm_utils.py
  tests/osm/test_osm_utils.py
Labels: bug
